[[v7-migration]]
:description: This page lists the breaking changes from version 6.0.0 to 7.0.0 and describes how to update.
:page-aliases: guides/index.adoc, guides/migration-guide/index.adoc, guides/migration-guide/server.adoc, \
guides/migration-guide/queries.adoc, guides/migration-guide/type-definitions.adoc, guides/migration-guide/mutations.adoc

= Migration to 7.0.0

This page lists all breaking changes from the Neo4j GraphQL Library version 6.x to 7.x and how to update it.

== How to update

To update your Neo4j GraphQL Library, use npm or the package manager of choice:

[source, bash, indent=0]
----
npm update @neo4j/graphql
----

== Breaking changes

Here is a list of all the breaking changes from version 6.0.0 to 7.0.0.

=== Removed the `@unique` directive

The `@unique` directive is no longer supported:


[source, graphql, indent=0]
----
type Movie {
    title: String! @unique()
}
----


=== Deprecated single element relationships

Single element relationships have been deprecated in favor of list relationships:

[source, graphql, indent=0]
----
[cols="1,1"]
|===
|Before | Now
a|
[source, graphql, indent=0]
----
type Movie {
    director: Person @relationship(type: "DIRECTED", direction: "IN")
}
----
a|
[source, graphql, indent=0]
----
type Movie {
    director: [Person!]! @relationship(type: "DIRECTED", direction: "IN")
}
----
|===



Single element relationships cannot be reliably enforced, leading to a data inconsistent with the schema.


=== `overwrite`


The `overwrite` argument in `connect` operations has been deprecated.
This is part of the overarching changes to how `connect` operations work in 7.x.

Instead, use the `update` operation to update a relationship.


=== Removed the `connectOrCreate` operation

The `connectOrCreate` operation has been removed due to limitations on its feature set when compared to other operations.

`connectOrCreate` relies on `MERGE` operations in Cypher, which did not allow for `onCreate` operations to follow nested relationships.
