[[v7-migration]]
:description: This page lists the breaking changes from version 6.0.0 to 7.0.0 and describes how to update.
:page-aliases: guides/index.adoc, guides/migration-guide/index.adoc, guides/migration-guide/server.adoc, \
guides/migration-guide/queries.adoc, guides/migration-guide/type-definitions.adoc, guides/migration-guide/mutations.adoc

= Migration to 7.0.0

This page lists all breaking changes from the Neo4j GraphQL Library version 6.x to 7.x and how to update it.

== How to update

To update your Neo4j GraphQL Library, use npm or the package manager of choice:

[source, bash, indent=0]
----
npm update @neo4j/graphql
----

== Breaking changes

Here is a list of all the breaking changes from version 6.0.0 to 7.0.0.

=== `@unique`

`@unique` directive is no longer supported:


[source, graphql, indent=0]
----
type Movie {
    title: String! @unique()
}
----


=== Non-list relationships

Deprecate single element relationships:


[source, graphql, indent=0]
----
type Movie {
    director: Person @relationship(type: "DIRECTED", direction: "IN")
}
----

In favor of list relationships:


[source, graphql, indent=0]
----
type Movie {
    director: [Person!]! @relationship(type: "DIRECTED", direction: "IN")
}
----

1-1 relationships cannot be reliably enforced, leading to a data inconsistent with the schema. For this reason, these have been removed in favor of the more accurate list relationships.


=== `overwrite`


Argument `overwrite` in `connect` operations has been deprecated. This is part of the overarching changes to how `connect` operation work in 7.x

For updating a relationship, use the `update` operation


=== `connectOrCreate`

The `connectOrCreate` operation has been removed due to limitations on its featureset when compared to other operations.

`connectOrCreate` relies on `MERGE` operations in Cypher, which did not allowed for `onCreate` operations to follow nested relationships.
